sonar.organization=toomas633
sonar.projectKey=Toomas633_Plex-Organizer
sonar.projectName=Plex Organizer

sonar.sourceEncoding=UTF-8
sonar.sources=plex_organizer/
sonar.python.version=3.10
sonar.issues.defaultAssigneeLogin=Toomas633@github

sonar.exclusions=

sonar.python.pylint.reportPaths=pylint-report.json
